name: tokenfinder
on:
    push:
      branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
        
      - name: Install depedencies
        run: yarn install --frozen-lockfile

      - name: Create env file
        run:  |
          touch .env
          echo BOTFATHER_API_KEY=${{secrets.BOTFATHER_API_KEY}} >> .env
          echo BITQUERY_API_KEY=${{secrets.BITQUERY_API_KEY}} >> .env
          echo DB_NAME=${{secrets.DB_NAME}} >> .env
          echo DB_HOST=${{secrets.DB_HOST}} >> .env
          echo DEXTOOLS_API_KEY=${{secrets.DEXTOOLS_API_KEY}} >> .env
        shell: bash
        
      - name: Stop all process
        run: |
          cd /home/actions-runner/token-finder/Bot0-TokenFinder
          pm2 stop ecosystem.config.js
        shell: bash

      - name: Start server 
        run: |
          cd /home/actions-runner/token-finder/Bot0-TokenFinder
          pm2 start ecosystem.config.js
        shell: bash
